version: '3.8'

services:
  avigilon-landing:
    container_name: avigilon-landing
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3010:3010" # Exposing on port 3010 (Host) -> 3010 (Container)
    environment:
      - NODE_ENV=production
    networks:
      - default
      - nginx_default

networks:
  default:
    driver: bridge
  nginx_default:
    external: true
